// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lprllsdtgnewmsnjyxhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxwcmxsc2R0Z25ld21zbmp5eGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3Mzc1MzAsImV4cCI6MjA2ODMxMzUzMH0.Jz0BFk2H73lwVqJ_8gcPwWhGsBiHcMFaZiGK1EN4PM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});